#ifndef ERRORMESSAGE_PRJ_H_INCLUDED
#define ERRORMESSAGE_PRJ_H_INCLUDED

#define ERROR_BUF_SIZE 4

#define ERROR_MESSAGE_LIST \
   ERROR_MESSAGE_ENTRY(CANTIMEOUT, ERROR_STOP) \
   ERROR_MESSAGE_ENTRY(PLCTIMEOUT, ERROR_STOP) \
   ERROR_MESSAGE_ENTRY(PRECTIMEOUT, ERROR_STOP) \
   ERROR_MESSAGE_ENTRY(LOCKTIMEOUT, ERROR_STOP) \
   ERROR_MESSAGE_ENTRY(EVSEFAULT, ERROR_STOP) \
   ERROR_MESSAGE_ENTRY(RELAYWELDED, ERROR_STOP) \

#endif // ERRORMESSAGE_PRJ_H_INCLUDED
